# -*- coding: utf-8 -*-
"""Week_6_Project_ Aspen_Fitness_Studio

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LBGPi95EQ4b6vYV2HDb4IMWBAZa5iAGG
"""

# Calculate and analyze month over month growth.
avg_rev =df['Revenue_USD'].mean()
best_month = df.loc[df['Revenue_USD'].idxmax(), ['Month_Name','Revenue_USD']]
worst_month = df.loc[df['Revenue_USD'].idxmin(), ['Month_Name','Revenue_USD']]
print(f'Average revenue: ${avg_rev:,.0f}')
print(f'Best month: {best_month['Month_Name']}(${best_month['Revenue_USD']:,.0f})')
print(f'Worst month:{worst_month['Month_Name']}(${worst_month['Revenue_USD']:,.0f})')
print()

import pandas as pd
import matplotlib.pyplot as plt

csv_path = '/content/aspen_fitness_studio_2024.csv'  # upload file first
df = pd.read_csv(csv_path)

print(df.head(13))
print()
print(df.info())
print()
print('Descriptive Statistics:')
print(df.describe().T)
print()
# Calculate and analyze month over month growth.
avg_rev =df['Revenue_USD'].mean()
best_month = df.loc[df['Revenue_USD'].idxmax(), ['Month_Name','Revenue_USD']]
worst_month = df.loc[df['Revenue_USD'].idxmin(), ['Month_Name','Revenue_USD']]
print(f'Average revenue: ${avg_rev:,.0f}')
print(f'Best month: {best_month['Month_Name']}(${best_month['Revenue_USD']:,.0f})')
print(f'Worst month:{worst_month['Month_Name']}(${worst_month['Revenue_USD']:,.0f})')
print()
# Create a line chart of revenue by month.
plt.figure(figsize=(9,4))
plt.plot(df['Month_Name'], df['Revenue_USD'], marker='o')
plt.title('Monthly Revenue - Aspen Fitness Studio')
plt.ylabel('Revenue (USD)')
plt.xlabel('Months')
plt.grid(True, axis='y', alpha=0.3)
plt.show()
print()
# Calculate and analyze month over month growth.
df['Revenue_MoM_%'] = df['Revenue_USD'].pct_change().round(4)*100
print('Month over month revenue change:')
print(df[['Month_Name', 'Revenue_USD', 'Revenue_MoM_%']])
print()
# display only the months with loss revenue growth
revenue_loss = df[df['Revenue_MoM_%'] < 0]
print('Months with revenue loss (Loss MoM change):')
print(revenue_loss[['Month_Name', 'Revenue_USD', 'Revenue_MoM_%']])
print()
# churned members greater than 50
churn_above_50 = df[df['Churned_Members'] > 50]
print('Months with churned members above 50:')
print(churn_above_50[['Month_Name', 'Churned_Members']])
print()