# -*- coding: utf-8 -*-
"""Week_8_Project_Part_3_ Aspen_Fitness_Studio

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B04wNLLt8fYP-uDpAJ5tL9csePkv7G4k
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("/content/aspen_fitness_studio_2023_2024.csv")

print(df.head())
print()
print(df.info())
print()
print(df.describe().T)
print()

# derived & Average metrics
df['trial_conversion_rate'] = df['Trial_Conversions'] / df['Free_Trial_Claims']
df['churn_rate'] = df['Churned_Members'] / df['Active_Members']
df['trial_conversion_rate'] = df['Trial_Conversions'] / df['Free_Trial_Claims'] * 100
df['churn_rate'] = df['Churned_Members'] / df['Active_Members'] * 100
df['net_adds'] = df['New_Members'] - df['Churned_Members']
df['ARPM'] = df['Revenue_USD'] / df['Active_Members']
print("Derived & Avergae metrics:")
df_2023 = df[df['Year'] == 2023]
df_2024 = df[df['Year'] == 2024]
print("Derived & Average Metrics (2023):")
print(df_2023[['trial_conversion_rate', 'churn_rate', 'net_adds', 'ARPM', 'Marketing_Spend_USD']].describe().T)
print()
print("Derived & Average Metrics (2024):")
print(df_2024 [['trial_conversion_rate', 'churn_rate', 'net_adds', 'ARPM', 'Marketing_Spend_USD']].describe().T)
print()
# Sum of marketing spend & New members in 2023 & 2024
print('Sum of marketing spend & New members in 2023 & 2024')
print(f"Total Marketing spend in 2023:",df_2023['Marketing_Spend_USD'].sum())
print(f"Total Marketing spend in 2024:",df_2024['Marketing_Spend_USD'].sum())
print(f"Total New Members in 2023:",df_2023['New_Members'].sum())
print(f"Total New Members in 2024:",df_2024['New_Members'].sum())
print()
# Print the top 3 Trial months.
highest_conversion = (df.sort_values('trial_conversion_rate', ascending=False)
.head(3)[['Year', 'Month', 'trial_conversion_rate', 'Free_Trial_Claims', 'Trial_Conversions']])
print("highest trial conversion months:")
print(highest_conversion)
print()
# Print Lowest trial conversion rate months
lowest_conversion = (df.sort_values('trial_conversion_rate', ascending=True)
.head(3)[['Year', 'Month', 'trial_conversion_rate', 'Free_Trial_Claims', 'Trial_Conversions']])
print("Lowest trial conversion months:")
print(lowest_conversion)
print()
# Print Trial Conversion & revenue percentage with months of lots of snow
snow_high_snow_days = df[df['Snow_Days'] >= 5]
print('Trial Conversion & revenue percentage with months of lots of snow')
print(snow_high_snow_days[['Month_Name', 'Snow_Days', 'Avg_Class_Rating','trial_conversion_rate', 'Revenue_USD']])
print()

print('Insight 1: Trial conversion rates exhibit seasonality with higher')
print('conversions in winter months, likely influenced by snow days and holiday periods.')
print()
# Print months with low Rating that is less than 4.5.
low_rating = df[df['Avg_Class_Rating'] < 4.5]
print('Months with low Rating than 4.5 but highest New Members joined')
print(low_rating[['Month_Name', 'New_Members', 'Avg_Class_Rating', 'Class_Capacity_Utilization_%', 'trial_conversion_rate']])
print()
# Months with utilization ≥ 85% and rating dip (< 4.5)
high_util_low_rating = df[(df['Class_Capacity_Utilization_%'] >= 85) & (df['Avg_Class_Rating'] < 4.5)]
print("Months with utilization >= 85% and Avg Class Rating < 4.5:")
print(high_util_low_rating[['Year', 'Month', 'Class_Capacity_Utilization_%', 'Avg_Class_Rating']])
print()
# Competitor promo months
competitor_promo_months = df[df['Competitor_Promo'] == True]
print("Competitor promo months:")
print(competitor_promo_months[['Year', 'Month', 'Competitor_Promo']])
print()
# Print Lowest trial conversion rate months
highest_churned = (df[df['NAU_In_Session'] == False].sort_values('Churned_Members', ascending=False)
.head(5)[['Year', 'Month', 'Churned_Members', 'trial_conversion_rate', 'Free_Trial_Claims', 'Trial_Conversions', 'NAU_In_Session']])
print("Highest churned members in months when NAU is false:")
print(highest_churned)
print()
# correlation between Free Trials vs New Members
trial_corr = df['Active_Members'].corr(df['Revenue_USD'])
print('Correlation (Active Members vs. Revenue USD):', round(trial_corr,2))
print()
# Average free Trails claims
print(f'Free trails claims:',df['Free_Trial_Claims'].mean())
print()

# Figure 1 — Line: Revenue by Month and Year
plt.figure(figsize=(10,4))
for yr, sub in df.groupby('Year'):
    plt.plot(sub['Month_Name'], sub['Revenue_USD'], marker='o', label=str(yr))
plt.title('Aspen Fitness Revenue by Month (2023–2024)')
plt.xlabel('Month')
plt.ylabel('Revenue (USD)')
plt.legend()
plt.tight_layout()
plt.show()
print()

# Figure 2 — Line: Percentage of Revenue from Pickups by Month and Year
plt.figure(figsize=(10,4))
for yr, sub in df.groupby('Year'):
    plt.plot(sub['Month_Name'], sub['trial_conversion_rate'], marker='o', label=str(yr))
plt.title('Aspen Fitness Percentage of Revenue from Trial Conversions by Month (2023–2024)')
plt.xlabel('Month')
plt.ylabel('Percentage of Revenue (%)')
plt.legend()
plt.tight_layout()
plt.show()
print()

# Figure 3: Average Revenue per Member (ARPM), 2023–2024
plt.figure(figsize=(10,4))
for yr, sub in df.groupby('Year'):
    plt.plot(sub['Month_Name'], sub['ARPM'], marker='o', label=str(yr))
plt.title('Average Revenue per Member (ARPM), 2023–2024')
plt.xlabel('Month')
plt.ylabel('ARPM (USD)')
plt.legend()
plt.tight_layout()
plt.show()
print()
print()
print("Insights from 2023-2024 revenue and percentage of revenue from pickups analysis:")
print("Insight: Revenue has remained relatively consistent and with similar")
print("seasonal patterns across 2023 and 2024.")
print("Insight: The percentage of revenue from trial conversions shows a seasonal")
print("pattern with higher percentages in the winter months and lower percentages")
print("in the summer months.")
print("Insight: The seasonality patterns are generally consistent across both")
print("years, but 2024 shows more sporadic ups and downs.")
print()

# Figure 4 - Combined: Pickup Revenue Percentage (%) and Snow Days by Month 2023
fig, ax1 = plt.subplots(figsize=(10,4))
ax1.plot(
    df[df['Year'] == 2023]['Month_Name'],
    df[df['Year'] == 2023]['trial_conversion_rate'],
    color='tab:blue',
    marker='o',
    label='Percentage Revenue'
)
ax1.set_ylabel('Percentage of Revenue from Trial Conversions')
ax2 = ax1.twinx()
ax2.bar(
    df[df['Year'] == 2023]['Month_Name'],
    df[df['Year'] == 2023]['Snow_Days'],
    color='tab:orange',
    alpha=0.4,
    label='Snow Days'
)
plt.title('Percentage of Revenue from Trial Conversions vs. Snow Days 2023')
plt.show()
print()

# Figure 5 - Combined: Pickup Revenue Percentage (%) and Snow Days by Month 2024
fig, ax1 = plt.subplots(figsize=(10,4))
ax1.plot(
    df[df['Year'] == 2024]['Month_Name'],
    df[df['Year'] == 2024]['trial_conversion_rate'],
    color='tab:blue',
    marker='o',
    label='Percentage Revenue'
)
ax1.set_ylabel('Percentage of Revenue from Trial Conversions')
ax2 = ax1.twinx()
ax2.bar(
    df[df['Year'] == 2024]['Month_Name'],
    df[df['Year'] == 2024]['Snow_Days'],
    color='tab:orange',
    alpha=0.4,
    label='Snow Days'
)
plt.title('Percentage of Revenue from Trial Conversions vs. Snow Days 2024')
plt.show()
print()
# Figure 6 - Combined: ARPM vs Churned Members by Month 2023
fig, ax1 = plt.subplots(figsize=(10,4))
ax1.plot(
    df[df['Year'] == 2023]['Month_Name'],
    df[df['Year'] == 2023]['ARPM'],
    color='tab:blue',
    marker='o',
    label='Percentage Revenue'
)
ax1.set_ylabel('Average Revenue Per Member (ARPM)')
ax2 = ax1.twinx()
ax2.bar(
    df[df['Year'] == 2023]['Month_Name'],
    df[df['Year'] == 2023]['Churned_Members'],
    color='tab:orange',
    alpha=0.4,
    label='Snow Days'
)
plt.title('Average Revenue Per Member (ARPM) vs. Churned Members 2023')
plt.show()
print()

# Figure 7 - Combined: ARPM vs Churned Members by Month by Month 2024
fig, ax1 = plt.subplots(figsize=(10,4))
ax1.plot(
    df[df['Year'] == 2024]['Month_Name'],
    df[df['Year'] == 2024]['ARPM'],
    color='tab:blue',
    marker='o',
    label='Percentage Revenue'
)
ax1.set_ylabel('Average Revenue Per Member (ARPM)')
ax2 = ax1.twinx()
ax2.bar(
    df[df['Year'] == 2024]['Month_Name'],
    df[df['Year'] == 2024]['Churned_Members'],
    color='tab:orange',
    alpha=0.4,
    label='Snow Days'
)
plt.title('Average Revenue Per Member (ARPM) vs. Churned Members 2024')
plt.show()
print()

