# -*- coding: utf-8 -*-
"""Week_7_Project_Part_2_ Aspen_Fitness_Studio

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19V16bgiV-LqMN94AcU4hxq327xUzMlvf
"""

import pandas as pd
import matplotlib.pyplot as plt

csv_path = '/content/aspen_fitness_studio_2024.csv'
df = pd.read_csv(csv_path)

print(df.head(13))
print()
print(df.info())
print()
print('Descriptive Statistics:')
print(df.describe().T)
print()

# How effective is our makreting?
#Look at correlation between marketing spend and revenue.
corr_now = df[['Marketing_Spend_USD', 'Revenue_USD']].corr().iloc[0, 1]
print('The correlation coefficient for Marketing and Revenue:')
print(corr_now)
print()
direct_corr = df['Revenue_USD'].corr(df['Marketing_Spend_USD'])
print(f"Same-month correlation (no lag): {direct_corr:.2f}")
print()
# correlation between NAU in Session and revenue.
nau_corr = df['Revenue_USD'].corr(df['NAU_In_Session'])
print('Correlation between NAU In Session and Revenue:', round(nau_corr,2))
print()

# correlation between Snow Days and revenue.
snow_corr = df['Revenue_USD'].corr(df['Snow_Days'])
print('Correlation between Snow Days and Revenue:', round(snow_corr,2))
print()
# correlation between Free Trials vs New Members
trial_corr = df['Free_Trial_Claims'].corr(df['New_Members'])
print('Correlation (Free Trials vs. New Members):', round(trial_corr,2))
print()

# Create a scatter to visualize te relationship between marketing and revenue.
plt.figure(figsize=(5,4))
plt.scatter(df['Marketing_Spend_USD'], df['Revenue_USD'])
plt.xlabel('Marketing Spend')
plt.ylabel('Revenue')
plt.title('Marketing Spend vs Revenue (USD)')
plt.show()
print()
# scatter to visualize te relationship between Free Trials vs. New Members.
plt.figure(figsize=(5,4))
plt.scatter(df['Free_Trial_Claims'], df['New_Members'])
plt.xlabel('Free Trials')
plt.ylabel('New Members')
plt.title('Free Trials vs. New Members')
plt.show()
print()
# Correlation analysis with marketing shifted by one month.
# Create a new column to hold shifted marketing values.
df['Marketing_Spend_Lagged'] = df['Marketing_Spend_USD'].shift(1)
corr_lag= df[['Marketing_Spend_Lagged', 'Revenue_USD']].corr().iloc[0,1]
print('Correlation coefficient of Marketing and revenue with marketing lagged.')
print(corr_lag)
print()
df['Marketing_Lag'] = df['Marketing_Spend_USD'].shift(1)
lagged_corr = df['Revenue_USD'].corr(df['Marketing_Lag'])
print(f"Correlation between prior month marketing spend and current revenue:{lagged_corr:.2f}")
print()
# Create a scatter to visualize te relationship between marketing and revenue.
plt.figure(figsize=(5,4))
plt.scatter(df['Marketing_Spend_Lagged'], df['Revenue_USD'])
plt.xlabel('Marketing Spend')
plt.ylabel('Revenue')
plt.title('Marketing Spend lagged by 1 months vs Revenue (USD)')
plt.show()
print()
print("Insight 1: Marketing has a strong positive relationship with revenue")
print("when we lag the marketing by one month. Another way to state this is")
print("we are realizing our revenue increase from marketing one monts after")
print("our spending on marketing")
print()
print("Insight 2: Free trials show a strong positive correlation with new member")
print("sign-ups at Aspen Fitness Studio. When free trial claims increase,")
print("new member enrollments rise in the same months. This suggests ongoing")
print("investment in free trials will be effective for membership growth.")
print()

# Service quality under load (customer reviews when busy)
# Ratings and review volume together
fig, ax1 = plt.subplots(figsize=(9,4))
ax1.plot(df['Month_Name'], df['Avg_Class_Rating'], color='tab:blue',
marker='o', label='Avg_Class_Rating')
ax1.axhline(4.4, color='gray', linestyle='--', linewidth=1)
ax1.set_ylabel('Avg Class Rating')
ax1.set_xlabel('Months')
ax2 = ax1.twinx()
ax2.bar(df['Month_Name'], df['Review_Count'], color='tab:orange',
alpha=0.3, label='Review Count')
ax2.set_ylabel('Number of Reviews')
plt.title('Ratings vs Review Volume')
plt.show()
print()
# Flag months where rating is low while review volume is high
top3_review_threshold = df['Review_Count'].nlargest(3).min()
flag = (df['Avg_Class_Rating'] < 4.4) & (df['Review_Count'] >= top3_review_threshold)
print('Months where rating is less than 4.4 and review count is in top 3:')
print(df.loc[flag, ['Month_Name','Avg_Class_Rating','Review_Count']])
print()

# Define peak season as months with revenue, active members, and new members above their yearly averages

avg_revenue = df['Revenue_USD'].mean()
avg_active = df['Active_Members'].mean()
avg_new = df['New_Members'].mean()

df['Peak_Revenue'] = df['Revenue_USD'] > avg_revenue
df['Peak_Active'] = df['Active_Members'] > avg_active
df['Peak_New'] = df['New_Members'] > avg_new
# Peak season where all three are True
df['Peak_Season_All'] = df['Peak_Revenue'] & df['Peak_Active'] & df['Peak_New']

print("Months identified as Peak Season (high in Revenue, Active Members, and New Members):")
print(df.loc[df['Peak_Season_All'], ['Month_Name', 'Revenue_USD', 'Active_Members', 'New_Members']])
print()

# External context (events, weather, NAU, competition)
print(df[['Month_Name','Snow_Days','NAU_In_Session','Nearby_Competitors','Free_Trial_Claims', 'Competitor_Promo']])
print()
# Peak season logic: Sep-Nov OR months with free trial
df['Peak_Season'] = df['Month'].isin([1,8,9,10]) | (df['Free_Trial_Claims'] > df['Free_Trial_Claims'].mean())
pct_revenue_peak = (df.loc[df['Peak_Season'], 'Revenue_USD'].sum() /df['Revenue_USD'].sum() * 100).round(1)
print('Percentage of Revenue Generated During Peak Season:')
print(pct_revenue_peak)
print()
# Peak season logic: Sep-Nov NAU inn session
df['NAU_Peak_Season'] = df['Month'].isin([1,8,9,10]) | (df['NAU_In_Session'] > df['NAU_In_Session'].mean())
nau_revenue_peak = (df.loc[df['NAU_Peak_Season'], 'Revenue_USD'].sum() / df['Revenue_USD'].sum() * 100).round(1)
print('Percentage of Revenue Generated During NAU Peak Season:')
print(nau_revenue_peak)
print()
# Decision framing (simple criteria → your recommendation)
last3 = df.tail(3) # Oct, Nov, Dec for this dataset
crit_rating = last3['Avg_Class_Rating'].mean() >= 4.5
crit_revenue = last3['Revenue_USD'].mean() >= df['Revenue_USD'].median()
criteria = f'Last 3 months avg rating ≥ 4.5: {crit_rating}\n'\
f'Last 3 months avg revenue ≥ median: {crit_revenue}'
print(criteria)

# Took help from AI to create this code to fetch more details about the data.
# Competitor count changes and effect on Revenue and Reviews
df['Competitor_Change'] = df['Nearby_Competitors'].diff().fillna(0)
new_competitor_months = df.loc[df['Competitor_Change'] > 0, ['Month_Name', 'Nearby_Competitors']]
print('\nMonths with new competitor arrivals:')
display(new_competitor_months)

# Compare average revenue, reviews, and active members before and after the first new competitor appearance
if not new_competitor_months.empty:
    first_comp_month = new_competitor_months.index[0]
    before = df.loc[:first_comp_month - 1]
    after = df.loc[first_comp_month:]
    avg_rev_before = before['Revenue_USD'].mean()
    avg_rev_after = after['Revenue_USD'].mean()
    revenue_drop_pct = ((avg_rev_before - avg_rev_after) / avg_rev_before) * 100
    print('\nAvg Revenue before new competitor:', before['Revenue_USD'].mean())
    print('Avg Revenue after new competitor:', after['Revenue_USD'].mean())
    print('Revenue dropped by:', round(revenue_drop_pct, 2), '%')
    print('Avg Reviews before new competitor:', before['Review_Count'].mean())
    print('Avg Reviews after new competitor:', after['Review_Count'].mean())
    print('Avg Active Members before new competitor:', before['Active_Members'].mean())
    print('Avg Active Members after new competitor:', after['Active_Members'].mean())
else:
    print('\nNo new competitors added in this period.')
print()